name: CI

on:
  push:
    branches: [ main, refactor-next ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: {}

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - uses: actions/checkout@v4
      - name: Use Node 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: backend/package.json
      - name: Install deps
        run: npm install
      - name: Run tests
        run: npm test
      - name: Backup artifact
        run: npm run backup
      - name: Upload backup
        uses: actions/upload-artifact@v4
        with:
          name: backend-backup-${{ github.sha }}
          path: backend/backups/*
          if-no-files-found: ignore
